// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Career", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LifePath")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Careers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "You are a natural leader — careers in management, entrepreneurship, and decision-making fit you.",
                            LifePath = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "You work well with people — careers in HR, counseling, teaching, or diplomacy suit you.",
                            LifePath = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "You are creative and expressive — fields like design, writing, or communication are ideal.",
                            LifePath = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "You are disciplined and practical — engineering, IT, operations, or project management fit you.",
                            LifePath = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "You are adaptable and energetic — sales, travel, marketing, and public-facing roles fit you well.",
                            LifePath = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "You are nurturing and responsible — education, healthcare, and community-focused roles suit you.",
                            LifePath = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "You are analytical and reflective — research, data science, IT, and technical roles are ideal.",
                            LifePath = 7
                        },
                        new
                        {
                            Id = 8,
                            Description = "You are ambitious and business-minded — finance, leadership, or management roles match your strengths.",
                            LifePath = 8
                        },
                        new
                        {
                            Id = 9,
                            Description = "You are compassionate and artistic — nonprofit, counseling, teaching, or creative work fits you well.",
                            LifePath = 9
                        });
                });

            modelBuilder.Entity("NumerologyResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BirthDay")
                        .HasColumnType("int");

                    b.Property<string>("Career")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Expression")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LifePath")
                        .HasColumnType("int");

                    b.Property<int>("Personality")
                        .HasColumnType("int");

                    b.Property<int>("SoulUrge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NumerologyResults");
                });
#pragma warning restore 612, 618
        }
    }
}
